name: CI/CD Pipeline

# Trigger workflow on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Step 5: Test
      - name: Test
        run: dotnet test --no-build --verbosity normal

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t yourdockerhubusername/insuranceapp:latest .
          docker push yourdockerhubusername/insuranceapp:latest
